- name: Start the AdminServer
  become: yes
  shell: "sudo amazon-linux-extras install nginx1.12 -y"
- name: start nginx
  service:
      name: nginx
      state: started
- name: delete
  file: 
    path: "/etc/nginx/conf.d/default.conf"
    state: absent    
- name: Overwrite file if it exists, the remote server has the source file bc remote_src is set below
  copy:
    src: "{{ role_path }}/files/nginx.conf" 
    dest: /etc/nginx/nginx.conf
